language: android
android:
  components:
  - tools
  - platform-tools
  - android-29
  - build-tools-28.0.3
  - extra-android-m2repository
  - extra-android-support

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check javadoc

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
